# **DIVIDE Y VENCERAS: Multiplicación de Matrices**

In [1]:
import numpy as np

## Multiplicacion de matrices utilizando la funcion matmul de la libreria numpy 

(explicacion en Python https://appdividend.com/2022/02/17/np-matmul/)

In [12]:
#Funcion que recibe dos vectores y retorna un vector con su multiplicacion.  Matmul es una funcion de la libreria numpy
def matmul(a, b):
  aRows, aCols = a.shape
  bRows, bCols = b.shape
  if aCols != bRows:
    return None

  c = np.zeros((aRows, bCols))

  for i in range(aRows):
    for j in range(bCols):
      temp = 0
      for k in range(aCols):
        temp += a[i, k] * b[k, j]

      c[i, j] = temp

  return c

In [13]:
# Creamos dos vectores con numeros aleatorios (entre 0 y 10)
# el vector a con 3 filas y 4 columnas
# el vector b con 4 filas y 2 columnas
a = np.random.randint(10, size=(3, 4))
b = np.random.randint(10, size=(4, 2))

print(a)
print(b)

[[2 9 7 6]
 [9 9 7 7]
 [9 1 8 4]]
[[7 5]
 [6 4]
 [9 5]
 [5 2]]


In [15]:
c = matmul(a, b)
assert c.all() == np.matmul(a, b).all()
print(c)

[[161.  93.]
 [215. 130.]
 [161.  97.]]


## Multiplicacion de matrices desarrollando una funcion recursiva.

In [16]:
# Multiplicar a y c.  El resultado guardarlo en c.  Los parametros i y j parten de 0.  Los parametros ii y jj inician con la logitud de la matriz a - 1
def matmul(a, b, c, i, ii, j, jj):
  if i == ii:
    temp = 0
    for k in range(len(a)):
      temp += a[i][k] * b[k][j]
    c[i][j] = temp
  else:
    imid = (i + ii) // 2
    jmid = (j + jj) // 2
    matmul(a, b, c,        i, imid,        j, jmid)
    matmul(a, b, c, imid + 1,   ii,        j, jmid)
    matmul(a, b, c,        i, imid, jmid + 1, jj)
    matmul(a, b, c, imid + 1,   ii, jmid + 1, jj)

In [17]:
# Matrices a y b random de 8x8 con numeros entre 0 y 8
a = np.random.randint(10, size=(8, 8))
b = np.random.randint(10, size=(8, 8))
print(a)
print(b)

[[5 3 4 6 0 4 8 4]
 [7 6 9 4 4 1 3 4]
 [3 0 4 2 7 4 6 0]
 [6 9 9 9 1 9 1 1]
 [5 5 5 0 1 0 7 2]
 [3 9 4 7 8 3 1 0]
 [3 3 0 3 2 7 7 0]
 [0 4 7 6 6 3 7 0]]
[[0 4 0 1 9 2 5 0]
 [5 1 4 5 3 8 1 0]
 [8 7 8 8 5 0 0 4]
 [5 1 9 6 6 1 0 0]
 [7 1 1 3 6 0 7 9]
 [2 8 8 6 4 5 6 4]
 [5 9 5 4 0 7 2 2]
 [4 9 2 1 7 9 8 1]]


In [18]:
#Obtenemos en la matriz c la multiplicacion de las matrices a y b
#Para que usamos assert? shorturl.at/fgKV9

c = np.zeros((8, 8))
matmul(a, b, c, 0, len(a) - 1, 0, len(a) - 1)
assert (c == np.matmul(a, b)).all()
print(c)

[[141. 197. 178. 148. 154. 152. 100.  52.]
 [183. 176. 167. 167. 206. 128. 113.  86.]
 [129. 135. 119. 116. 117.  70. 100. 107.]
 [196. 196. 269. 239. 229. 154. 110.  84.]
 [115. 142. 100. 103. 105. 117.  67.  45.]
 [179.  97. 168. 168. 176. 107. 100. 102.]
 [ 93. 139. 132. 112.  94. 117.  88.  60.]
 [189. 152. 191. 176. 131. 102.  78. 108.]]
